### ISSUE TITLE
Broken link - MyMusic

### ISSUE THREAD

**Issue by JuanPabloDiaz** [szymonrybczak/szymonrybczak.dev#6]
Hey bro, 
I am not sure if you are aware, but you have a broken link in your site: [mymusic.pl](https://mymusic.pl/)

![image](https://github.com/szymonrybczak/szymonrybczak.dev/assets/25883220/07171b08-0fe1-4bd8-a4de-cd3b4ad042e1)

![image](https://github.com/szymonrybczak/szymonrybczak.dev/assets/25883220/18c33904-4579-458a-810b-51eaeaed99e8)

**Comment by szymonrybczak** [comment]
hey! thanks for spotting this :pray: Fixed in this commit: https://github.com/szymonrybczak/szymonrybczak.dev/commit/cd1ce9c01a8390c3940f5152673e7fe4ed8326c7
